connection:
  access_token: NWJiZjY2NGYtY2I5YS1jN2Y4LTMwZTktYjU1Mi04NDA4NDMzODpkNzU0ZmU3MC1jZDY2LTExZTgtOGJjZC01ZDNlMmQ1ZDc1NTQ=
  master_host: apimation.com:9000
worker:
  type: loc
  port: 9675
  job_limit: 200
  debug: false
  dev: false
  log_path: /Users/dlocmelis/prezentacijas/signal2018/worker/logs/worker
