connection:
  access_token: NWJiZTAzMGMtNjlmYS1hZWEyLWU4NmUtYzQyMC00YjRiMTMwZDoxNzFjYzNhMC1jYzkzLTExZTgtOGJjZC01ZDNlMmQ1ZDc1NTQ=
  master_host: apimation.com:9000
worker:
  type: loc
  port: 9675
  job_limit: 200
  debug: false
  dev: false
  log_path: /Users/dlocmelis/prezentacijas/signal2018/worker/logs/worker
