connection:
  access_token: NWJjNzdhZjktNGNkOS04NTIxLWI1OWItYTg1NC1iZTc5ZWI2NTpkYTc3MGViMC1kMjM3LTExZTgtOGJjZC01ZDNlMmQ1ZDc1NTQ=
  master_host: apimation.com:9000
worker:
  type: loc
  port: 9675
  job_limit: 200
  debug: false
  dev: false
  logOnlyToFile: true
  log_path: /Users/dlocmelis/demo/signal2018/worker/logs/worker
